load("@com_google_protobuf//:protobuf.bzl", "py_proto_library")

proto_library(
    name = "app_proto",
    srcs = ["app.proto"],
)

py_proto_library(
    name = "app_proto_py",
    srcs = ["app.proto"],
)
